"""add_grade

Revision ID: f6375221e9a1
Revises: d044c678b789
Create Date: 2026-06-09 09:21:52.461248
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f6375221e9a1'
down_revision: Union[str, None] = 'd044c678b789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('grade', sa.String(length=16), server_default='', nullable=False))
    op.alter_column('mistakes', 'subject',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mistakes', 'subject',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('mistakes', 'grade')
    # ### end Alembic commands ###
